# Generated by Django 5.2.13 on 2026-04-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название устройства')),
                ('expected_os_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Название ОС')),
                ('expected_cpu_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Название процессора')),
                ('max_cpu_load', models.FloatField(default=80.0, verbose_name='Максимальная допустимая нагрузка CPU (%)')),
                ('min_free_disk_gb', models.IntegerField(default=10, verbose_name='Минимальное свободное место (ГБ)')),
            ],
            options={
                'verbose_name': 'Устройство',
            },
        ),
    ]
