# Generated by Django 5.2.13 on 2026-04-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'Node'},
        ),
    ]
