# Generated by Django 5.2.13 on 2026-04-21 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node_monitoring", "0005_metrictype"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeMetricHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=255, verbose_name="Текущее значение метрики")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                ("is_valid", models.BooleanField(default=False, verbose_name="Успешность")),
                (
                    "validation_message",
                    models.CharField(blank=True, max_length=255, verbose_name="Дополнительная информация"),
                ),
                (
                    "metric_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="node_monitoring.metrictype",
                        verbose_name="Метрика",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_history",
                        to="node_monitoring.node",
                        verbose_name="Устройство",
                    ),
                ),
            ],
            options={
                "verbose_name": "История метрики",
                "verbose_name_plural": "Истории метрик",
                "indexes": [
                    models.Index(fields=["node", "metric_type", "-created_at"], name="node_monito_node_id_5bb047_idx"),
                    models.Index(fields=["-created_at"], name="node_monito_created_00ec11_idx"),
                ],
            },
        ),
    ]
